use std::{
    env,
    fs::File,
    io::{BufWriter, Write},
    path::PathBuf,
};

fn main() {
    println!("cargo:rerun-if-env-changed=SOURCEID");

    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let path = &out.join("source_id.rs");
    let mut file = BufWriter::new(File::create(path).unwrap());

    let soource_id_code = match env::var("SOURCEID") {
        Ok(val) => {
            let num: u8 = val.parse().expect("SOURCEID must be valid u8!");
            format!("Some({})", num)
        }
        Err(_) => "None".to_string(),
    };

    write!(
        &mut file,
        "{}",
        format_args!(
            "\
            // Generated by build.rs\n\
            const SOURCEID: Option<u8> = {};\n",
            soource_id_code
        )
    )
    .unwrap();

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}
