use std::{
    env,
    fs::File,
    io::{BufWriter, Write},
    path::PathBuf,
};

fn main() {
    println!("cargo:rerun-if-env-changed=SOURCEID");
    println!("cargo:rerun-if-env-changed=KP");
    println!("cargo:rerun-if-env-changed=KI");

    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let path = &out.join("source_id.rs");
    let mut file = BufWriter::new(File::create(path).unwrap());

    let source_id_code = match env::var("SOURCEID") {
        Ok(val) => {
            let num: u8 = val.parse().expect("SOURCEID must be valid u8!");
            format!("Some({})", num)
        }
        Err(_) => "None".to_string(),
    };
    let kp_code = match env::var("KP") {
        Ok(val) => {
            let num: i64 = val.parse().expect("KP must be valid i64!");
            format!("Some({})", num)
        }
        Err(_) => "None".to_string(),
    };
    let ki_code = match env::var("KI") {
        Ok(val) => {
            let num: i64 = val.parse().expect("KI must be valid i64!");
            format!("Some({})", num)
        }
        Err(_) => "None".to_string(),
    };
    write!(
        &mut file,
        "{}",
        format_args!(
            "\
            // Generated by build.rs\n\
            const SOURCEID: Option<u8> = {};\n\
            const KP: Option<i64> = {};\n\
            const KI: Option<i64> = {};\n",
            source_id_code, kp_code, ki_code
        )
    )
    .unwrap();

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}
