[package]
name = "must-hop"
version = "0.1.3"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A multi hop network orchestrator, implementing LoRa functionality with lora-rs and BLE functionality with trouBLE"
repository = "https://github.com/jakobolason/must-hop"

[dependencies]

defmt = "1.1.1"
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
postcard = { version = "1.1.3", default-features = false, features = [] }
heapless = { version = "0.9.3", features = ["serde"] }
embassy-time = { version = "0.5.0", features = [] }
embassy-sync = { version = "0.8.0" }

log = { version = "0.4.33", optional = true }

embedded-hal = { version = "1.0.0", optional = true }

# For LoRa functionality
lora-phy = { workspace = true, optional = true }
lora-modulation = { workspace = true, optional = true }


[features]
default = [
  "postcard/defmt",
  "postcard/use-defmt",
  "heapless/defmt",
  "embassy-time/defmt",
  "embassy-time/defmt-timestamp-uptime",
  "embassy-sync/defmt",
]

in_std = [
  "log",
  "embassy-time/std",
  "serde/std",
  "embassy-time/generic-queue-8",
]
debug = ["embedded-hal"]
lora = ["lora-phy", "lora-modulation"]

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt", "time"] }
