[package]
name = "must-dash"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
ansi-to-tui = "8.0.1"
strip-ansi-escapes = "0.2.1"
portable-pty = "0.9.0"

tokio = { version = "1.52.1", features = ["full"] }
nix = { version = "0.31.2", features = ["signal"] }

regex = "1.12.3"

log = "0.4.29"
simplelog = "0.12.2"
chrono = "0.4.44"
dotenv = "0.15.0"
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
